version: '3'

services:
  fastapi:
    build: fastapi/
    environment:
        - PORTFastapi=${PORTFastapi}
    ports:
        - ${PORTFastapi}:${PORTFastapi}
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build:             
         dockerfile: ./Dockerfile
         context: .
    depends_on:
      - fastapi
    environment:
        - PORTStreamlit=${PORTStreamlit}
    ports:
        - ${PORTStreamlit}:${PORTStreamlit}
    networks:
      - deploy_network
    container_name: streamlitg

networks:
  deploy_network:
    driver: bridge